version: "3.8"

services:
  api:
    build:
      context: ./OrdersApp/OrdersApp
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      CONNECTION_STRING: "Data Source=(localdb)\\MSSQLLocalDB;Initial Catalog=AykhanOrdersDataBase;Integrated Security=True;Connect Timeout=30;Encrypt=False;Trust Server Certificate=False;Application Intent=ReadWrite;Multi Subnet Failover=False"

  db:
    image: mcr.microsoft.com/mssql/server
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"

  react-app:
    build:
      context: ./orders-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: "http://api:5000"
